### ISSUE TITLE
编译时候报错，日志如下，烦请大神帮助指导

### ISSUE THREAD

**Issue by MxCen** [peter-tank/openwrt-minisign#2]
> make[4]: Entering directory '/home/lede/lede/build_dir/target-x86_64_musl/minisign/minisign-0.8.0-9727843b70c4c385ee3259644a45e0e2d5de0f33'
make[5]: Entering directory '/home/lede/lede/build_dir/target-x86_64_musl/minisign/minisign-0.8.0-9727843b70c4c385ee3259644a45e0e2d5de0f33'
make[6]: Entering directory '/home/lede/lede/build_dir/target-x86_64_musl/minisign/minisign-0.8.0-9727843b70c4c385ee3259644a45e0e2d5de0f33'
make[6]: Leaving directory '/home/lede/lede/build_dir/target-x86_64_musl/minisign/minisign-0.8.0-9727843b70c4c385ee3259644a45e0e2d5de0f33'
make[6]: Entering directory '/home/lede/lede/build_dir/target-x86_64_musl/minisign/minisign-0.8.0-9727843b70c4c385ee3259644a45e0e2d5de0f33'
[ 20%] Building C object CMakeFiles/minisign.dir/src/minisign.c.o
In file included from /home/lede/lede/build_dir/target-x86_64_musl/minisign/minisign-0.8.0-9727843b70c4c385ee3259644a45e0e2d5de0f33/src/minisign.c:19:0:
/home/lede/lede/build_dir/target-x86_64_musl/minisign/minisign-0.8.0-9727843b70c4c385ee3259644a45e0e2d5de0f33/src/minisign.h:39:28: error: 'crypto_pwhash_scryptsalsa208sha256_SALTBYTES' undeclared here (not in a function); did you mean 'crypto_pwhash_argon2i_SALTBYTES'?
     unsigned char kdf_salt[crypto_pwhash_scryptsalsa208sha256_SALTBYTES];
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                            crypto_pwhash_argon2i_SALTBYTES
/home/lede/lede/build_dir/target-x86_64_musl/minisign/minisign-0.8.0-9727843b70c4c385ee3259644a45e0e2d5de0f33/src/minisign.c: In function 'seckey_load':
/home/lede/lede/build_dir/target-x86_64_musl/minisign/minisign-0.8.0-9727843b70c4c385ee3259644a45e0e2d5de0f33/src/minisign.c:371:9: warning: implicit declaration of function 'crypto_pwhash_scryptsalsa208sha256'; did you mean 'crypto_pwhash_scryptsalsa208sha256_OPSLIMIT_MIN'? [-Wimplicit-function-declaration]
     if (crypto_pwhash_scryptsalsa208sha256
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         crypto_pwhash_scryptsalsa208sha256_OPSLIMIT_MIN
/home/lede/lede/build_dir/target-x86_64_musl/minisign/minisign-0.8.0-9727843b70c4c385ee3259644a45e0e2d5de0f33/src/minisign.c: In function 'generate':
/home/lede/lede/build_dir/target-x86_64_musl/minisign/minisign-0.8.0-9727843b70c4c385ee3259644a45e0e2d5de0f33/src/minisign.c:666:20: error: 'crypto_pwhash_scryptsalsa208sha256_OPSLIMIT_SENSITIVE' undeclared (first use in this function); did you mean 'crypto_pwhash_scryptsalsa208sha256_OPSLIMIT_MIN'?
     kdf_opslimit = crypto_pwhash_scryptsalsa208sha256_OPSLIMIT_SENSITIVE;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    crypto_pwhash_scryptsalsa208sha256_OPSLIMIT_MIN
/home/lede/lede/build_dir/target-x86_64_musl/minisign/minisign-0.8.0-9727843b70c4c385ee3259644a45e0e2d5de0f33/src/minisign.c:666:20: note: each undeclared identifier is reported only once for each function it appears in
/home/lede/lede/build_dir/target-x86_64_musl/minisign/minisign-0.8.0-9727843b70c4c385ee3259644a45e0e2d5de0f33/src/minisign.c:667:20: error: 'crypto_pwhash_scryptsalsa208sha256_MEMLIMIT_SENSITIVE' undeclared (first use in this function); did you mean 'crypto_pwhash_scryptsalsa208sha256_OPSLIMIT_SENSITIVE'?
     kdf_memlimit = crypto_pwhash_scryptsalsa208sha256_MEMLIMIT_SENSITIVE;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    crypto_pwhash_scryptsalsa208sha256_OPSLIMIT_SENSITIVE
make[6]: *** [CMakeFiles/minisign.dir/build.make:102: CMakeFiles/minisign.dir/src/minisign.c.o] Error 1
make[6]: Leaving directory '/home/lede/lede/build_dir/target-x86_64_musl/minisign/minisign-0.8.0-9727843b70c4c385ee3259644a45e0e2d5de0f33'
make[5]: *** [CMakeFiles/Makefile2:73: CMakeFiles/minisign.dir/all] Error 2
make[5]: Leaving directory '/home/lede/lede/build_dir/target-x86_64_musl/minisign/minisign-0.8.0-9727843b70c4c385ee3259644a45e0e2d5de0f33'
make[4]: *** [Makefile:152: all] Error 2
make[4]: Leaving directory '/home/lede/lede/build_dir/target-x86_64_musl/minisign/minisign-0.8.0-9727843b70c4c385ee3259644a45e0e2d5de0f33'
make[3]: *** [Makefile:93: /home/lede/lede/build_dir/target-x86_64_musl/minisign//minisign-0.8.0-9727843b70c4c385ee3259644a45e0e2d5de0f33/.built] Error 2
make[3]: Leaving directory '/home/lede/openwrt-extra/minisign/openwrt-minisign'
time: package/openwrt-extra/minisign-feeds/compile#0.13#0.02#0.16
make[2]: *** [package/Makefile:109: package/openwrt-extra/minisign-feeds/compile] Error 2
make[2]: Leaving directory '/home/lede/lede'
make[1]: *** [package/Makefile:103: /home/lede/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/lede/lede'
make: *** [/home/lede/lede/include/toplevel.mk:218: world] Error 2

**Comment by MxCen** [comment]
Openwrt是Lean大神开源。

**Comment by peter-tank** [comment]
libsodium 要改 #1
